// GLOBAL CONTEXT ACTIONS
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
export const UPDATE_RENDERED_PRODUCTS = "UPDATE_RENDERED_PRODUCTS";
export const FILTER_PRODUCTS_CATEGORY = "FILTER_PRODUCTS_CATEGORY";

// CART CONTEXT ACTIONS
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const HANDLE_ITEM_CART_QUANTITY = "HANDLE_ITEM_CART_QUANTITY";
export const HANDLE_WISHLIST = "HANDLE_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const MOVE_ALL_WISHLIST_TO_CART = "MOVE_ALL_WISHLIST_TO_CART";
